insert into achievements (name, description, icon, condition_type, condition_value, category) values
('Langkah Pertama', 'Mencatat berat badan pertama.', 'scale', 'weight_log_count', 1, 'berat'),
('Turun 3kg', 'Berhasil menurunkan berat 3 kg.', 'scale', 'weight_loss_kg', 3, 'berat'),
('Turun 5kg', 'Berhasil menurunkan berat 5 kg.', 'scale', 'weight_loss_kg', 5, 'berat'),
('Turun 10kg', 'Berhasil menurunkan berat 10 kg.', 'scale', 'weight_loss_kg', 10, 'berat'),
('Setengah Jalan', 'Mencapai 50% dari target penurunan berat.', 'target', 'weight_goal_percent', 50, 'berat'),
('Berat Ideal', 'Mencapai rentang berat ideal.', 'badge-check', 'reached_ideal_weight', 1, 'berat'),
('Turun 20kg', 'Berhasil menurunkan berat 20 kg.', 'scale', 'weight_loss_kg', 20, 'berat'),
('Latihan Pertama', 'Menyelesaikan workout pertama.', 'dumbbell', 'workout_completed', 1, 'workout'),
('Seminggu Konsisten', 'Latihan 7 hari berturut-turut.', 'calendar', 'workout_streak_days', 7, 'workout'),
('HIIT Warrior', 'Menyelesaikan 10 sesi HIIT.', 'zap', 'hiit_sessions', 10, 'workout'),
('Iron Man', 'Menyelesaikan 20 sesi strength training.', 'shield', 'strength_sessions', 20, 'workout'),
('Streak 30 Hari', 'Aktif 30 hari berturut-turut.', 'flame', 'activity_streak_days', 30, 'workout'),
('100 Workout', 'Mencapai 100 workout total.', 'trophy', 'workout_completed', 100, 'workout'),
('Chef Sehat', 'Melog makanan sehat selama 7 hari.', 'chef-hat', 'meal_log_days', 7, 'meal'),
('Protein Master', 'Mencapai target protein selama 7 hari.', 'beef', 'protein_target_days', 7, 'meal'),
('Disiplin Kalori', 'Tetap dalam target kalori selama 14 hari.', 'gauge', 'calorie_target_days', 14, 'meal'),
('30 Hari Makan Sehat', 'Melog pola makan sehat selama 30 hari.', 'salad', 'meal_log_days', 30, 'meal'),
('Kegel Starter', 'Menyelesaikan sesi kegel pertama.', 'circle-dot', 'kegel_sessions', 1, 'kegel'),
('Kegel Warrior', 'Konsisten kegel selama 30 hari.', 'timer', 'kegel_days', 30, 'kegel'),
('Kegel Master', 'Konsisten kegel selama 60 hari.', 'sparkles', 'kegel_days', 60, 'kegel'),
('PSMF Survivor', 'Berhasil melewati fase 1-2.', 'mountain', 'phase_completed', 1, 'fase'),
('HIIT Beginner', 'Memasuki fase conditioning.', 'bolt', 'phase_completed', 2, 'fase'),
('Getting Stronger', 'Memasuki fase strength rebuild.', 'armchair', 'phase_completed', 3, 'fase'),
('Almost There', 'Masuk fase maintenance.', 'rocket', 'phase_completed', 4, 'fase'),
('Program Complete', 'Menyelesaikan 24 minggu program.', 'crown', 'phase_completed', 5, 'fase'),
('Pengukuran Pertama', 'Mencatat measurement pertama.', 'ruler', 'measurement_log_count', 1, 'ukuran'),
('Progres Nyata', 'Panjang proyeksi bertambah 1 cm.', 'expand', 'length_gain_cm', 1, 'ukuran')
on conflict (name) do update set
  description = excluded.description,
  icon = excluded.icon,
  condition_type = excluded.condition_type,
  condition_value = excluded.condition_value,
  category = excluded.category;
